### ISSUE TITLE
File is not a database: , while compiling: select count(*) from sqlite_master

### ISSUE THREAD

**Issue by LadwaAditya** [commonsguy/cwac-saferoom#24]
Receiving the following error when performing a delete operation

E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:158)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:120)
        at android.arch.persistence.room.RoomDatabase.compileStatement(RoomDatabase.java:204)
        at android.arch.persistence.room.SharedSQLiteStatement.createNewStatement(SharedSQLiteStatement.java:65)
        at android.arch.persistence.room.SharedSQLiteStatement.getStmt(SharedSQLiteStatement.java:72)
        at android.arch.persistence.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.java:87)

**Comment by commonsguy** [comment]
Please read [the documentation for getting help with this library](https://github.com/commonsguy/cwac-saferoom#questions) and [the documentation for filing bug reports](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports).

If you feel that this is a bug in the library, then you will need to follow [those instructions for filing bug reports](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports) and provide in this issue:

- the Android OS version on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that version of Android, to reproduce the problem

I cannot help you given only a stack trace. Note that you will get this error whenever the supplied passphrase is invalid.

**Comment by LadwaAditya** [comment]
`Note that you will get this error whenever the supplied passphrase is invalid` helps

**Comment by Goran1708** [comment]
what is a valid passphrase?

**Comment by Goran1708** [comment]
```Room.databaseBuilder(context, MyLocalDatabase.class, "my-db").allowMainThreadQueries()
        .openHelperFactory(new SafeHelperFactory("passphrase".toCharArray()))
            .fallbackToDestructiveMigration().build();
```

I'm getting that if I do it like this.

**Comment by Goran1708** [comment]
This is happening on nexus 4 emulator with 22 API but it is not happening on nexus 6P 27 API emulator. Using same code.

**Comment by Goran1708** [comment]
Sorry seems I did not remove my application so it was trying to decrypt/encrypt existing file. Is there a migration for existing room databases, something like `fallbackToDestructiveMigration`? Or should we just delete old file?

**Comment by commonsguy** [comment]
@Goran1708 You can use [`SQLCipherUtils.encrypt()` to encrypt an existing database](https://github.com/commonsguy/cwac-saferoom#encrypting-existing-databases).

**Comment by Goran1708** [comment]
Ah sorry I understand. Thank you.
