### ISSUE TITLE
SqlCipher doesn't like not closed statment 

### ISSUE THREAD

**Issue by SelvinPL** [commonsguy/cwac-saferoom#3]
```
W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: DELETE FROM T1 WHERE uri=?
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
	at pl.selvin.android.db.sqlcipher.SqlCipherDatabase.compileStatement(SqlCipherDatabase.java:58)
	at pl.selvin.android.db.sqlcipher.SqlCipherDatabase.delete(SqlCipherDatabase.java:186)
	at pl.selvin.android.syncframework.content.TableInfo.DeleteWithUri(TableInfo.java:212)
	at pl.selvin.android.syncframework.content.BaseContentProvider.sync(BaseContentProvider.java:588)
	at pl.osadkowski.mobiletrader.syncadapter.SyncService$SyncAdapter.onPerformSync(SyncService.java:204)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```
Yeah, it's from mine library but implementation is almost identical, so I think it's worth to report here

Problem appears in delete method of SupportSQLiteDatabase.delete (by calling it directly - I'm not sure if Room is using it - it may have it's own implementation)

It's only appears as log statment (prolly ex.printstactrace() from sqlcipher code) ...
But if we do lot's of delete statments app crash

```
       java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
	   at java.lang.Object.wait(Native Method)
	   at java.lang.Thread.parkFor$(Thread.java:2135)
	   at sun.misc.Unsafe.park(Unsafe.java:358)
	   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	   at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
	   at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:900)
	   at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1223)
	   at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:225)
	   at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:286)
	   at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:553)
	   at net.sqlcipher.database.SQLiteCompiledSql.releaseSqlStatement(SQLiteCompiledSql.java:106)
	   at net.sqlcipher.database.SQLiteCompiledSql.finalize(SQLiteCompiledSql.java:152)
	   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
	   at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
	   at java.lang.Daemons$Daemon.run(Daemons.java:103)
	   at java.lang.Thread.run(Thread.java:764)
```
so solution is:

```
    @Override
    //we shouldn't worry about AutoClosable nor try-with-resources - they are working fine on API lower than 19
    @SuppressLint("NewApi")
    public int delete(String table, String whereClause, Object[] whereArgs) {
        String query = "DELETE FROM " + table
                + (isEmpty(whereClause) ? "" : " WHERE " + whereClause);
        try {
            try (SupportSQLiteStatement statement = compileStatement(query)) {
                SimpleSQLiteQuery.bind(statement, whereArgs);
                return statement.executeUpdateDelete();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return -1;
    }
```

By the way thanx for BindingsRecorder hack ... i was missing it in my implementation

**Comment by commonsguy** [comment]
Thanks for pointing this out! That solution is kinda nasty, though: eating an exception is a really bad idea. I will see if I can reproduce this problem and, if so, will use `try`/`finally` or something to close the statement(?) while still allowing exceptions to propagate.

**Comment by SelvinPL** [comment]
yeah, you are right ... I've change `ex.printStackTrace()` to throw `new RuntimeException(ex);` ... but clue of the solution was to close SQLiteStatement right after usage

**Comment by commonsguy** [comment]
I cannot seem to reproduce this problem, even when calling `delete()` directly. What version of SQLCipher for Android are you using? What version of Android and `android.arch.persistence:db` are you using that reproduces this problem?

**Comment by SelvinPL** [comment]
Emulator API 26 (not crash but spamming logcat with:
```
11-13 23:59:14.927 6343-6352/pl.selvin.android.deleteissuemvce W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: DELETE FROM Test WHERE C1=?
                                                                                    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                                        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
                                                                                        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
                                                                                        at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
                                                                                        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1589)
                                                                                        at com.commonsware.cwac.saferoom.Database.compileStatement(Database.java:52)
                                                                                        at com.commonsware.cwac.saferoom.Database.delete(Database.java:257)
                                                                                        at pl.selvin.android.deleteissuemvce.MainActivity$2.run(MainActivity.java:37)
                                                                                        at java.lang.Thread.run(Thread.java:764)
```
)
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final SafeHelperFactory factory= SafeHelperFactory.fromUser(new SpannableStringBuilder("test"));
        final SupportSQLiteOpenHelper.Callback callback = new SupportSQLiteOpenHelper.Callback(1) {
            @Override
            public void onCreate(SupportSQLiteDatabase db) {
                db.execSQL("CREATE TABLE IF NOT EXISTS Test(C1 INTEGER PRIMARY KEY NOT NULL, C2 TEXT NOT NULL)");
            }

            @Override
            public void onUpgrade(SupportSQLiteDatabase db, int oldVersion, int newVersion) {

            }
        };
        final SupportSQLiteOpenHelper.Configuration config = SupportSQLiteOpenHelper.Configuration.builder(this).name("test")
                .callback(callback).build();
        final SupportSQLiteOpenHelper helper = factory.create(config);
        final SupportSQLiteDatabase db = helper.getWritableDatabase();
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i = 0; i < 10000; i++) {
                    db.delete("Test", "C1=?", new String[]{"1"});
                }
                Log.e("DeleteIssue", "End");
            }
        }).start();

    }
```


```
dependencies {
    implementation 'com.commonsware.cwac:saferoom:0.1.1'
    implementation 'android.arch.persistence:db:1.0.0'
    implementation 'net.zetetic:android-database-sqlcipher:3.5.7'
}
```

**Comment by commonsguy** [comment]
Bizarre. The messages only show up with a sufficiently high number of passes of your loop. 1400 does not trigger it, but 1500 does (at least sometimes).

But, the loop now gives me a failing test case, so I can work on fixing matters. Thanks!

**Comment by SelvinPL** [comment]
prolly depends on internal GC.collect call

**Comment by commonsguy** [comment]
Addressed in v0.1.2 &mdash; many thanks!

**Comment by dbof10** [comment]
still happens for me with 1.1.1

**Comment by commonsguy** [comment]
@dbof10 Per [the project contribution guidelines](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md), I need:

- the Android OS version on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that version of Android, to reproduce the problem

**Comment by pmolcany** [comment]
Happens to me when leakcanary is enabled, version `2.0-beta-3`

**Comment by commonsguy** [comment]
@pmolcany If you can provide me:

- the Android OS version on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that version of Android, to reproduce the problem

...then I can try to reproduce the problem.
