### ISSUE TITLE
COLLATION: SQLiteException: no such collation sequence: UNICODE (AndroidX)

### ISSUE THREAD

**Issue by dunda123** [commonsguy/cwac-saferoom#30]
1. Empty DB, Class (table) User with column 

@ColumnInfo(collate = ColumnInfo.UNICODE, name="last_name")
String last_name;

When I call query:
Query("SELECT * FROM user ORDER BY last_name")

Error:
2018-10-23 10:16:06.643 17839-17914/cz.dunda.android.testy.roomtest E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
    Process: cz.dunda.android.testy.roomtest, PID: 17839
    net.sqlcipher.database.SQLiteException: no such collation sequence: UNICODE: CREATE TABLE IF NOT EXISTS `User` (`uid` INTEGER PRIMARY KEY AUTOINCREMENT, `first_name` TEXT NOT NULL, `last_name` TEXT NOT NULL COLLATE UNICODE)
        at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
        at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
        at com.commonsware.cwac.saferoom.Database.execSQL(Database.java:350)
        at cz.dunda.android.testy.roomtest.AppDatabase_Impl$1.createAllTables(AppDatabase_Impl.java:33)
        at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:74)
        at com.commonsware.cwac.saferoom.Helper$1.onCreate(Helper.java:52)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:171)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:157)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:119)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:251)
        at androidx.room.util.DBUtil.query(DBUtil.java:54)
        at cz.dunda.android.testy.roomtest.UserDao_Impl$3.compute(UserDao_Impl.java:237)
        at cz.dunda.android.testy.roomtest.UserDao_Impl$3.compute(UserDao_Impl.java:223)
        at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)

Without Saferoom is all ok.

2. Insert
Error:
net.sqlcipher.database.SQLiteException: no such collation sequence: UNICODE: CREATE TABLE IF NOT EXISTS `User` (`uid` INTEGER PRIMARY KEY AUTOINCREMENT, `first_name` TEXT NOT NULL, `last_name` TEXT NOT NULL COLLATE UNICODE)

If I don't use Saferoom, insert and query work correctly and sorting too.

Thank you for your help and this library.

Zdenek.

**Comment by commonsguy** [comment]
I believe that is a limitation of the current version of SQLCipher for Android. Nothing in SafeRoom itself should be affecting this.

I suggest that you create a scrap project and connect directly to SQLCipher, then try running the failing statement (`CREATE TABLE IF NOT EXISTS User (uid INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT NOT NULL, last_name TEXT NOT NULL COLLATE UNICODE)`). If you get the same error, then the limitation is in SQLCipher for Android, and you will need to check with them for your options.

If, on the other hand, this works with plain SQLCipher fro Android, but fails with SafeRoom, then that is clearly a problem with SafeRoom, and I can work to fix it. In that case, comment back on this issue, and I can reopen it and investigate further.

**Comment by dunda123** [comment]
When I off CWAC on database builder, Error not throwed. I create test project [TestRoomCollate](https://github.com/dunda123/TestRoomCollate). Please watch TODO for comments for you.
Thank you for help.
Sorry for my English.

**Comment by dunda123** [comment]
I've probably found a bug in SqlCipher. Please watch [here](https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515/13)

**Comment by dunda123** [comment]
It's bad, sorting is very important for the database, and SafeRoom (SQLCipher) is the only alternative for security Room database.
Thank you for your time.
