### ISSUE TITLE
Not thread safe execution of OpenHelper#setupWAL

### ISSUE THREAD

**Issue by antslava** [commonsguy/cwac-saferoom#33]
[OpenHelper#setupWAL](https://github.com/commonsguy/cwac-saferoom/blob/167221d386b57354e4580a2ca4582c74fdf1e3be/saferoom/src/main/java/com/commonsware/cwac/saferoom/Helper.java#L183) can be called on multiple threads, and because access to field [walEnabled](https://github.com/commonsguy/cwac-saferoom/blob/167221d386b57354e4580a2ca4582c74fdf1e3be/saferoom/src/main/java/com/commonsware/cwac/saferoom/Helper.java#L150) is not synchronized, that can lead to `NullPointerException`. Which I got on the current project.
Exception looks like:
```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.commonsware.cwac.saferoom.Helper$OpenHelper.setupWAL(SourceFile:186)
       at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(SourceFile:162)
       at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(SourceFile:120)
       at android.arch.persistence.room.RoomDatabase.query(SourceFile:233)
       at com.hidden_package.SomeDao_Impl$2.call(SourceFile:65)
       at com.hidden_package.SomeDao_Impl$2.call(SourceFile:62)
       at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(SourceFile:46)
       at io.reactivex.Maybe.subscribe(SourceFile:3727)
       at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(SourceFile:46)
       at io.reactivex.Single.subscribe(SourceFile:2779)
       at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SourceFile:34)
       at io.reactivex.Single.subscribe(SourceFile:2779)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SourceFile:89)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
My suggestion will be to synchronize this field inside method [OpenHelper#setupWAL](https://github.com/commonsguy/cwac-saferoom/blob/167221d386b57354e4580a2ca4582c74fdf1e3be/saferoom/src/main/java/com/commonsware/cwac/saferoom/Helper.java#L183).

P.S.
I was able to reproduce this issue with unit tests, but reproducibility is unstable. To make it stable, we need to use specific tool which can help us to synchronize threads. (Like https://github.com/google/thread-weaver etc.).
If you need a more detailed step to reproduce I can provide it to you.

**Comment by commonsguy** [comment]
I took a different approach for now, putting synchronization on `Helper` and `OpenHelper`. v0.4.5 (Android Support Library) and v0.5.1 (AndroidX) add this.

Reportedly, the next version of SQLCipher for Android will be released soon. After it does, I will be rewriting SafeRoom to avoid some of my hacks, and I will ensure that I take synchronization into account there as well. I'm hoping that SafeRoom will be a bit simpler and therefore make the synchronization simpler as well.

Thanks for pointing this out!

**Comment by erikhuizinga** [comment]
Do you know how soon the next SQLCipher for Android will be released?

I know about [this post](https://discuss.zetetic.net/t/sqlcipher-for-android-room-and-api-level-16/2161/30) about SQLCipher for Android, but I don't know if I have to wait weeks, months or even longer. Do you happen to know more?

**Comment by commonsguy** [comment]
@erikhuizinga They are saying [late November](https://discuss.zetetic.net/t/sqlcipher-sqlite-update/2470/17?u=commonsguy) at the moment.

**Comment by antslava** [comment]
@commonsguy, you are welcome and thanks for a useful library.
