### ISSUE TITLE
can't open encrypted database

### ISSUE THREAD

**Issue by hannesa2** [commonsguy/cwac-saferoom#41]
### A
I run into following after error update from `com.commonsware.cwac:saferoom.x:0.5.1` to `com.commonsware.cwac:saferoom.x:1.0.0-alpha1`

### B
on some devices, most are HTC One_M8, just one single Pixel 3, I see the crash without update to `1.0.0-alpha1` just using `com.commonsware.cwac:saferoom.x:0.5.1`

Any ideas ?

```
    java.lang.RuntimeException: Unable to create application net.demo.partnerapp.CouchApp: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1954)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1840)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2571)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2502)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1204)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1267)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:142)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:77)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:238)

```

**Comment by commonsguy** [comment]
For A, make sure you follow [the instructions for opening or upgrading an older database](https://github.com/commonsguy/cwac-saferoom/blob/master/README-1.0.0.md#usage).

For A or B, perhaps you entered in the wrong passphrase.

**Comment by hannesa2** [comment]
### For A:

Ok, I missed this. Thank you for your hint.
So everyone has to take care about the migrations, why this lib doesn't make this step automatically ?
But when I see the spirit of this repo, I see no sense to make a PR.
**Please add such a migration logic**, everyone will be happy about this !

### For B:

We do a fresh install, with same (what else on a fresh install ?) password and we see it on one device Pixel 3 (other Pixel 3 are working) and in crashlytics of approximately ~ < 0,5 % . Please @originx correct me, if I'm wrong 
Ok, that's not much, but with > 5.000.000 users it's a lot !

We can't reproduce it in a common way. But we are happy to see it at least on one device in our hands.
It crashes in `net.sqlcipher.database.SQLiteCompiledSql.native_compile`
So it seems to be device dependent, but we don't understand under which circumstances. Most of them are Huawei

Any ideas ? Or how to help to investigate.

**Comment by originx** [comment]
@hannesa2 I had this issue on fresh install of the app (so database migration is not an issue) also the password was hardcoded string explicitly to exclude the suspect of wrong password
Since it fails on the native_compile(SQL_STATEMENT) im sorry to say but  I cannot assist with the creation of a reproduction case since it goes to native code and thus I do not understand fully what is going on there. If there is something to try out, test, or set some settings I can do this but other than that without the help of creators of sqlcipher or commonsguy its just tapping in the dark.

hope you find the root cause, cheers

**Comment by commonsguy** [comment]
> why this lib doesn't make this step automatically ?

I have no way of knowing whether the database uses the old format, the new format, some custom cipher settings, etc.

> Or how to help to investigate.

Since that is the exception that you will get for an invalid passphrase, perhaps the users are entering an invalid passphrase. You will also get this exception if:

- You are attempting to open an unencrypted database
- You are attempting to open a database that has been modified (tampering attempts, hardware-caused data corruption, etc.)
- Possibly other reasons, as this exception comes from SQLCipher for Android, not from SafeRoom

**Comment by hannesa2** [comment]
> I have no way of knowing whether the database uses the old format, the new format, some custom cipher settings, etc.

Me too. So I've to set an extra info about db migration state outside of Room for each database we use in our app (we have four modules using each an own cwac-saferoom), eg in SharedPreferences.
To be honest, I see no reason why cwac-saferoom can't do this too
