### ISSUE TITLE
App crashing after upgrading version

### ISSUE THREAD

**Issue by Goran1708** [commonsguy/cwac-saferoom#53]
I upgrade the app from version:
`implementation "com.commonsware.cwac:saferoom:0.4.5"`
to 
`implementation "com.commonsware.cwac:saferoom.x:1.0.4"`
In the meantime we switched from android support library to androidx library.
Now we are using:
`implementation "androidx.room:room-runtime:2.0.0"`

When I run the app I get this crash:
`
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1898)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2647)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2577)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1243)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1318)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:142)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:77)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:238)
`

Is that because of some compatibility issue between version 0.4.5 and 1.0.4 and because android because we switched from android support room to androidx room?

**Comment by commonsguy** [comment]
Did you follow [the instructions for migrating from SafeRoom 0.x to 1.x](https://github.com/commonsguy/cwac-saferoom#upgrading-to-100-and-higher)?

**Comment by Goran1708** [comment]
Yup, tried both of them.

**Comment by Goran1708** [comment]
I was using this so far `new SafeHelperFactory(SECRET_KEY.toCharArray());` if that makes any difference?

**Comment by commonsguy** [comment]
That's not new -- the `byte[]` version of `SafeHelperFactory()` is the new one.

Note that if `SECRET_KEY` is a constant, that's not a safe thing to use, as [SafeRoom zeros out the passphrase that you supply](https://github.com/commonsguy/cwac-saferoom#supplying-a-passphrase). Besides, a constant key is pointless from a security standpoint.

SQLCipher for Android should not care whether you are using the AndroidX or Support Library version of SafeRoom, as it has no idea that either of those things exist.

Try `implementation "com.commonsware.cwac:saferoom.x:0.4.5" with an old copy of the database. If that works, then try 1.0.2 (with the 0.x -> 1.x migration code), then 1.0.4, and see where the problem crops up. Basically, we need to identify a smaller change that triggers your crash.

**Comment by Goran1708** [comment]
If I go to "com.commonsware.cwac:saferoom.x:0.5.0"(...x:0.4.5 does not exist), it works. But if I jump to 1.0.0 and above it starts crashing with that crash that is in the first comment.

**Comment by Goran1708** [comment]
I understand that secret key is a bit pointless but still, its better then having unencrypted database. This would be decrypt-able if attacker got the key from source code(which I know is possible). Getting key from server or on user input does not work with our app.

**Comment by commonsguy** [comment]
> If I go to "com.commonsware.cwac:saferoom.x:0.5.0"(...x:0.4.5 does not exist), it works. But if I jump to 1.0.0 and above it starts crashing with that crash that is in the first comment.

That really feels like you are not quite correctly applying [the 0.x to 1.x migration](https://github.com/commonsguy/cwac-saferoom#upgrading-to-100-and-higher) post-key SQL.

> its better then having unencrypted database

Considering the amount of disk space that SQLCipher for Android requires, I am very skeptical that you are significantly improving user security here.

**Comment by Goran1708** [comment]
Ah sorry about that...
`new SafeHelperFactory(SECRET_KEY.toCharArray(), SafeHelperFactory.POST_KEY_SQL_V3);` This works... Although could you tell me the difference `POST_KEY_SQL_V3` and `POST_KEY_SQL_MIGRATE `. I'm not sure I understand what they are for exactly.

**Comment by commonsguy** [comment]
`POST_KEY_SQL_V3` says "I want to keep using the V3 database format". `POST_KEY_SQL_MIGRATE` says "I want to switch to the V4 database format".

Anyway, I am glad to hear that you stabilized things!

**Comment by hannesa2** [comment]
@Goran1708 We had several issues about this, approximately 1% of our users run into a unexplainable `net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;` 
I even asked multiple times here as well https://github.com/sqlcipher/android-database-sqlcipher/issues?q=is%3Aissue+is%3Aclosed but we/nobody could solved it.
1 % seams not much, but when you have millions of users, 1% is a huge amount !

So, we decide to go with plain Room. To Secure Room is promising, but when it's  not working properly it's useless, so we decided to leave this lib. -sorry-
