### ISSUE TITLE
Application did not close the cursor or database object that was opened here

### ISSUE THREAD

**Issue by 2fours** [commonsguy/cwac-saferoom#54]
I'm seeing this issue consistently using the androidx version 1.0.4, with room 2.1.0-rc01. It doesn't seem to hurt anything.

2019-06-05 12:27:59.177 31420-31438/com.twofours.surespot.sandbox W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: update groupmessages set plainData = ? where ourUsername = ? and gid = ? and iv = ?
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:109)
        at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1702)
        at com.commonsware.cwac.saferoom.Database.compileStatement(Database.java:54)
        at androidx.room.RoomDatabase.compileStatement(RoomDatabase.java:317)
        at androidx.room.SharedSQLiteStatement.createNewStatement(SharedSQLiteStatement.java:65)
        at androidx.room.SharedSQLiteStatement.getStmt(SharedSQLiteStatement.java:77)
        at androidx.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.java:87)
        at com.twofours.surespot.persistence.db.dao.GroupMessageDao_Impl.updatePlainText(GroupMessageDao_Impl.java:731)
        at com.twofours.surespot.persistence.SurespotRepository.setPlainText(SurespotRepository.java:747)
        at com.twofours.surespot.viewmodel.MessageViewModel.setPlainText(MessageViewModel.java:185)
        at com.twofours.surespot.chat.MessageDecryptor$DecryptionTask.run(MessageDecryptor.java:182)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by commonsguy** [comment]
That is coming from Room-generated code, so there is not much that I can do about it directly, particularly without a reproducible test case. If you can give me something that reproduces it, I can try figuring out exactly what Room is doing, then perhaps file an issue with the Architecture Components team.

**Comment by 2fours** [comment]
I could give you access to the latest version of my app code on bitbucket.

**Comment by commonsguy** [comment]
That's your call, but I'm not really in a position to sign some sort of agreement to see your code. [Contact me](mailto:mmurphy@commonsware.com) if you still want to go down this path.

Short of that, could you tell me what `GroupMessageDao` and `updatePlainText()` look like, and if there is anything unusual about the related entity class?

**Comment by commonsguy** [comment]
OK, this is a known bug-that-Google-claims-is-working-as-intended in Room: https://issuetracker.google.com/issues/112826483. Unless Room generates a better DAO implementation that closes its `Closeable` objects, you will get this warning.

**Comment by 2fours** [comment]
Thanks for getting to the bottom of that.
