### ISSUE TITLE
app get crashed when changing the database key from plain text to encrypted key

### ISSUE THREAD

**Issue by manishakamble** [commonsguy/cwac-saferoom#72]
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(Unknown Source:15)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(Unknown Source:43)
        at net.sqlcipher.database.SQLiteProgram.<init>(Unknown Source:116)
        at net.sqlcipher.database.SQLiteQuery.<init>(Unknown Source:0)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(Unknown Source:7)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(Unknown Source:35)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(Unknown Source:1)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(Unknown Source:30)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(Unknown Source:14)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(Unknown Source:14)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(Unknown Source:7)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source:91)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Unknown Source:4)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Unknown Source:6)
        at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(Unknown Source:0)
        at com.kioskengineproject.dao.DaoAccess_Impl.insertBins(Unknown Source:2)
        at com.kioskengineproject.repository.KioskEngineRepository$1.doInBackground(Unknown Source:12)
        at com.kioskengineproject.repository.KioskEngineRepository$1.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)

**Comment by commonsguy** [comment]
In general, this error message means that the passphrase that was used to try to decrypt the database was incorrect. If you would like further help, please [follow the instructions for getting support](https://github.com/commonsguy/cwac-saferoom#questions).

If you think that you have found a bug in SafeRoom, please [follow the instructions](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports) and provide:

- the Android OS version on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that version of Android, to reproduce the problem
